### PR TITLE
Underscore to dash in setup.py.

### PR DESCRIPTION
**Pull request by dwf**

### CODE REVIEW

**Comment by dwf** [comment]
D'oh, too quick.

**Comment by bartvm** [comment]
I'm a bit confused... The repo is with a dash, but Travis tries to clone it with an underscore? Did it change?

**Comment by bartvm** [comment]
Okay, disabling and re-enabling Travis seemed to fix that.

**Comment by dwf** [comment]
Yeah, I changed the repo from underscore to dash, to agree with PyPI and...
aesthetics.

**Pull request merged**
